server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  servlet:
    context-path: /oauth-web
spring:
  application:
    name: oauth-web
  profiles:
    active: @env@

 #数据库配置
  datasource:
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 28800
    testOnBorrow: false
    testWhileIdle: true
    testOnReturn: false
  #redis 配置
  redis:
    defaultExpireDay: 45  
    redisIndex: 0
    # 最小连接数目
    maxIdle: 50   
    # 最大数连接数
    maxActive: 1000 
    #立连接等待时间
    maxWait: 1000
    #连接是否可用
    testOnBorrow: true

  http:  
      encoding.charset: UTF-8  
      encoding.enable: true  
      encoding.force: true
            
  mvc: 
      view:  
          prefix: /WEB-INF/jsp/  
          suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.demo.oauth2.entity